services:
    web-server:
        image: nginx:alpine
        restart: unless-stopped
        container_name: nginx_pcms
        depends_on:
            - mariadb
            - php-fpm
        volumes:
            - ${WWW_PATH}:/var/www
            - ${CONF_PATH}/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ${CONF_PATH}/nginx/letsencrypt:/etc/nginx/letsencrypt
            - ${LOG_PATH}/nginx:/var/log/nginx
            - ${CONF_PATH}/nginx/sites/default.conf:/etc/nginx/conf.d/default.conf
            - run_vol:/var/run
        ports:
            - "${HOST_HTTP_PORT}:80"
            - "${HOST_HTTPS_PORT}:443"
        # networks:
        #     - elk_net
        #     - default
        working_dir: /var/www

    php-fpm:
        # image: andygott/php-fpm-alpine-imagick
        build: .
        image: php_pcms:191028
        restart: unless-stopped
        container_name: php-fpm_pcms
        depends_on:
            - mariadb
        links:
            - mariadb
        volumes:
            - ${WWW_PATH}:/var/www
            - ${CONF_PATH}/nginx/letsencrypt:/etc/nginx/letsencrypt
            - ${MYSQL_DATA_PATH}:/var/lib/mysql
            - ${CONF_PATH}/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/php-ini-overrides.ini
            - ${CONF_PATH}/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
        ports:
            - "${HOST_WS_PORT}:9527"
        working_dir: /var/www

    mariadb:
        image: mariadb:10.4.6
        container_name: mariadb_pcms
        restart: unless-stopped
        ports:
            - "${MYSQL_PORT}:3306"
        # networks:
        #     - elk_net
        #     - default
        volumes:
            - ${MYSQL_DATA_PATH}:/var/lib/mysql
            - ${LOG_PATH}/mysql:/var/log/mysql
            - ${CONF_PATH}/mysql/my.cnf:/etc/mysql/conf.d/settings.cnf
            - ${CONF_PATH}/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        command: ['mysqld', '--character-set-server=utf8mb4']
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - TZ=Asia/Taipei
    redis:
        image: redis:latest
        container_name: redis_pcms
        restart: unless-stopped
        ports:
            - "6379:6379"
        volumes:
            - ./../redis/redis.conf:/usr/local/etc/redis.conf
            - ./../../redis/data:/usr/local/redis/data
            - ./../../redis/redis.log:/usr/local/redis/redis.log
volumes:
    run_vol:
        driver_opts:
            type: tmpfs
            device: tmpfs
# networks:
#     elk_net:
#         external:
#             name: elk
